image: maven:3.8.3-openjdk-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository" #Used by pipeline
  MAVEN_CLI_OPTS: "--batch-mode -DskipUITests -DskipServerTests" #(still builds test-jars)

stages:
  - test
  - build


# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository
  key: "$CI_BUILD_REF_NAME"

test:
  stage: test
  script:
    - "cd travelu; mvn clean test $MAVEN_CLI_OPTS"
  artifacts:
    paths:
      - travelu/core/target/surefire-reports/*.xml
      - travelu/localpersistence/target/surefire-reports/*.xml

build:
  stage: build
  when: manual
  script:
    - "cd travelu; mvn clean install $MAVEN_CLI_OPTS"