@startuml 

component fxui {
  package travelu.fxui {
}
}

component localpersistence {
  package travelu.localpersistence {
}
}

component core {
  package travelu.core {
}
}

skinparam component{
  BorderColor #800080
  ArrowColor purple
  BackgroundColor orchid
}

skinparam package{
  BackgroundColor lightyellow
  BorderColor #8B0000
}

[fxml] 
[javafx]
[com.google.gson] 

fxui ...> fxml
fxui ...> javafx
localpersistence ...> fxml
localpersistence ...> javafx
localpersistence ..> com.google.gson

core ...> com.google.gson

travelu.fxui ..> travelu.core
travelu.fxui ..> travelu.localpersistence
travelu.localpersistence ..> travelu.fxui

@enduml