@startuml packageDiagram 
skin rose

component restserver {
  [travelu.restserver] <<inside>>
}

component fxui {
  package travelu.fxui {
}
}

component localpersistence {
  package travelu.localpersistence {
}
}

component core {
  package travelu.core {
}
}

component localpersistence {
  package travelu.localpersistence {
}
}

component spring {
  [boot] <<inside>>
}

component javafx {
  [fxml] <<inside>>
}

component google {
  [gson] <<inside>>
}

skinparam Component {
  BackgroundColor transparent
  BorderColor black
  BorderColor<<inside>> #cc1836
}

skinparam ComponentBorderThickness 1.2
skinparam PackageBorderThickness 1.2
skinparam PackageBorderColor black
skinparam ArrowColor #cc1836

HIDE <<inside>> stereotype


travelu.fxui ...> fxml
travelu.fxui ...> travelu.localpersistence
travelu.localpersistence ...> gson
travelu.core <...> travelu.localpersistence
travelu.restserver ...> travelu.core
travelu.restserver ...> boot
travelu.restserver ...> travelu.localpersistence
@enduml