@startuml packageDiagram 
skin rose

component restserver {
  [travelu.restserver]
}

component fxui {
  package travelu.fxui {
}
}

component core {
  package travelu.core {
}
}

component fxutil {
  package travelu.fxutil {
}
}

component spring {
  [boot] 
}

component javafx {
  [fxml] 
}


component google {
  [gson] 
}

travelu.fxui ...> fxml
travelu.fxui ...> travelu.fxutil
travelu.fxutil ...> gson
travelu.core <...> travelu.fxutil
travelu.restserver ...> travelu.core
@enduml