@startuml sequenceDiagram
skin rose
actor User as user
participant "addButton: Button" as addButton
participant "DestinationListController" as destListCon
participant "TraveluHandler" as persistence
participant "RestTemplate" as rest
participant "TraveluController" as tcon
participant "TraveluService" as tser
participant "TraveluListners" as tlist 
' maybe add this to the diagram

user --> addButton : Click on the "Add" button
addButton --> destListCon : addDestination
destListCon --> persistence : writeJSON
persistence --> rest : PostForObject("/destinations".destination)
rest --> tcon : POST: baseURL/destinations
tcon --> tser : addDestination
tser --> rest : HTTP:OK 200
rest --> persistence : HTTOP:OK 200
persistence --> user : New destination \nadded in the list

@enduml